openapi: 3.0.3
info:
  title: Destinations API
  version: 1.0.0
servers:
  - url: https://api.server.test/v1
paths:
  /destinations:
    get:
      summary: Get all destinations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Destination'
  /destinations/{id}:
    get:
      summary: Get destination by id
      parameters:
        - name: code
          in: path
          description: Destination Code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        '404':
          description: Not Found
    patch:
      summary: Update the code of a destination by ID
      parameters:
        - name: code
          in: path
          description: Destination Code
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found

    delete:
      summary: Delete a Destination
      parameters:
        - name: code
          in: query
          description: Destination code
          required: true
          schema:
            type: string

      responses:
        '204':
          description: No Content
        '404':
          description: No Content
components:
  schemas:
    Destination:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        hotelCodes:
          type: array
      required:
        - code
        - name
        - hotelCodes